#!/bin/bash
# Quick Deployment Script for Render

echo "🚀 BrandMark Backend Deployment Guide"
echo "======================================"
echo ""
echo "📋 Prerequisites:"
echo "   ✓ Render account created"
echo "   ✓ GitHub repository connected"
echo ""
echo "🔧 Deployment Steps:"
echo ""
echo "1. Go to: https://render.com/dashboard"
echo ""
echo "2. Click 'New +' → 'Web Service'"
echo ""
echo "3. Connect repository: irahulsinghrajput/BrandMark"
echo ""
echo "4. Configure settings:"
echo "   - Name: brandmark-backend"
echo "   - Branch: gh-pages"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo ""
echo "5. Add Environment Variables (from backend/.env):"
echo "   - MONGODB_URI"
echo "   - JWT_SECRET"
echo "   - EMAIL_USER"
echo "   - EMAIL_PASS"
echo "   - FRONTEND_URL=https://brandmarksolutions.site"
echo "   - NODE_ENV=production"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "7. Wait for deployment (3-5 minutes)"
echo ""
echo "8. Copy your backend URL (e.g., https://brandmark-backend.onrender.com)"
echo ""
echo "9. Update frontend files with production URL:"
echo "   - brandmark.js"
echo "   - career-form.js"
echo "   - admin-dashboard.html"
echo ""
echo "📖 Full Guide: DEPLOYMENT_GUIDE.md"
echo ""
read -p "Press Enter to continue..."
