#!/usr/bin/env node
/**
 * Direct Student Registration & Enrollment Utility
 * 
 * Usage:
 *   node backend/scripts/register-student.js <email> <password> [courseId] [name] [phone] [paymentId]
 * 
 * Example:
 *   node backend/scripts/register-student.js student@example.com MyPass123 digital-marketing "Student Name" "9876543210" "pay_manual_001"
 */

require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const connectDB = require('../config/db');
const Student = require('../models/Student');
const jwt = require('jsonwebtoken');

const COURSE_TITLES = {
    'digital-marketing': 'Digital Marketing Mastery with Gen AI',
    'full-stack-dev': 'Full Stack Web Development — MERN + GenAI',
    'digital-marketing-001': 'Digital Marketing Mastery with Gen AI',
    'fullstack-mern-001': 'Full Stack Web Development — MERN + GenAI'
};

const JWT_SECRET = process.env.JWT_SECRET || 'brandmark_super_secret_jwt_key_min_32_characters_long';

const args = process.argv.slice(2);

if (args.length < 2) {
    console.log(`
Usage:
  node backend/scripts/register-student.js <email> <password> [courseId] [name] [phone] [paymentId]

Options:
  email       Required: Student email address
  password    Required: Student account password (minimum 6 characters)
  courseId    Optional: 'digital-marketing' (default) or 'full-stack-dev'
  name        Optional: Student full name (default: "Student")
  phone       Optional: Student contact number
  paymentId   Optional: Razorpay payment id (default: autogenerated)
`);
    process.exit(1);
}

const [
    email,
    password,
    rawCourseId = 'digital-marketing',
    name = 'Enrolled Student',
    phone = '',
    paymentId = `manual_pay_${Date.now()}`
] = args;

const courseId = rawCourseId === 'full-stack' ? 'full-stack-dev' : rawCourseId;
const courseTitle = COURSE_TITLES[courseId] || COURSE_TITLES['digital-marketing'];

if (password.length < 6) {
    console.error('❌ Error: Password must be at least 6 characters long.');
    process.exit(1);
}

(async () => {
    try {
        console.log('🔌 Connecting to MongoDB...');
        await connectDB();

        let student = await Student.findOne({ email });

        if (student) {
            console.log(`ℹ️  Found existing student account for ${email} (ID: ${student._id})`);
            const alreadyEnrolled = student.enrolledCourses.some(c => c.courseId === courseId);
            if (alreadyEnrolled) {
                console.log(`⚠️  Student is ALREADY enrolled in "${courseTitle}".`);
            } else {
                student.enrolledCourses.push({
                    courseId,
                    courseTitle,
                    paymentId,
                    orderId: `manual_order_${Date.now()}`,
                    enrolledAt: new Date()
                });
                await student.save();
                console.log(`✅ Successfully added enrollment for "${courseTitle}"!`);
            }
        } else {
            console.log(`📝 Creating new student record for ${email}...`);
            student = await Student.create({
                name,
                email,
                phone,
                password,
                enrolledCourses: [{
                    courseId,
                    courseTitle,
                    paymentId,
                    orderId: `manual_order_${Date.now()}`,
                    enrolledAt: new Date()
                }]
            });
            console.log(`✅ Successfully created student account! (ID: ${student._id})`);
        }

        const token = jwt.sign(
            { id: student._id, email: student.email },
            JWT_SECRET,
            { expiresIn: '30d' }
        );

        console.log('\n================ STUDENT DETAILS ================');
        console.log(` Name:            ${student.name}`);
        console.log(` Email:           ${student.email}`);
        console.log(` Active Courses:  ${student.enrolledCourses.map(c => c.courseId).join(', ')}`);
        console.log(` Auth Token:      ${token.slice(0, 20)}...`);
        console.log('=================================================\n');

        process.exit(0);
    } catch (err) {
        console.error('❌ Failed to register student:', err.message);
        process.exit(1);
    }
})();
