import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Certificate } from './Certificate';

const dmQuestions = [
  { q: "What does AIDA stand for?", options: ["Attention, Interest, Desire, Action", "Awareness, Interaction, Decision, Action"], answer: 0 },
  { q: "Which tag is most critical for on-page SEO?", options: ["H1 Tag", "B Tag"], answer: 0 },
  { q: "What is a 'lookalike audience' in Meta Ads?", options: ["An audience built from your competitors' followers", "An audience generated by the algorithm that shares traits with your existing customers"], answer: 1 },
  { q: "What does CRO stand for?", options: ["Customer Retention Optimization", "Conversion Rate Optimization"], answer: 1 },
  { q: "Which metric is prioritized by the TikTok algorithm?", options: ["Watch Time & Completion Rate", "Total Follower Count"], answer: 0 }
];

const fsQuestions = [
  { q: "What is the Virtual DOM?", options: ["A lightweight JS representation of the real DOM", "A direct copy of the HTML file"], answer: 0 },
  { q: "Which hook manages side effects in React?", options: ["useState", "useEffect"], answer: 1 },
  { q: "What does RAG stand for in AI engineering?", options: ["Retrieval-Augmented Generation", "Randomized Algorithm Generator"], answer: 0 },
  { q: "Which is a NoSQL database?", options: ["PostgreSQL", "MongoDB"], answer: 1 },
  { q: "What is the primary benefit of Next.js Server Components?", options: ["They ship zero JavaScript to the client", "They render faster on slow mobile devices"], answer: 0 }
];

export const MockTest = ({ courseData }) => {
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);

  const questions = courseData === 'digital-marketing' ? dmQuestions : fsQuestions;
  const courseName = courseData === 'digital-marketing' ? "Digital Marketing Masterclass" : "Full Stack Developer with Gen AI";

  const handleAnswer = (selectedIndex) => {
    if (selectedIndex === questions[currentQuestion].answer) {
      setScore(score + 1);
    }
    
    if (currentQuestion + 1 < questions.length) {
      setCurrentQuestion(currentQuestion + 1);
    } else {
      setShowResult(true);
    }
  };

  const percentage = (score / questions.length) * 100;
  const passed = percentage >= 80;

  if (showResult) {
    return (
      <div className="bg-white p-8 rounded-3xl border border-brand-border-light shadow-sm text-center py-16">
        <h2 className="text-4xl font-bold text-brand-navy mb-4">
          {passed ? "Congratulations! 🎉" : "Keep Learning! 📚"}
        </h2>
        <p className="text-xl text-brand-text-body mb-8">
          You scored <strong className={passed ? "text-green-500" : "text-red-500"}>{percentage}%</strong> ({score}/{questions.length})
        </p>

        {passed ? (
          <div>
            <p className="text-brand-text-muted mb-8">You have successfully mastered the curriculum and earned your certification.</p>
            <Certificate 
              studentName="Verified Student" 
              courseName={courseName} 
              date={new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} 
            />
          </div>
        ) : (
          <div>
            <p className="text-brand-text-muted mb-8">You need an 80% to pass and unlock your certificate. Review the modules and try again!</p>
            <button 
              onClick={() => { setShowResult(false); setCurrentQuestion(0); setScore(0); }}
              className="px-8 py-3 bg-brand-navy text-white rounded-xl font-bold hover:bg-brand-navy-dark transition-colors"
            >
              Retake Mock Test
            </button>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="bg-white p-8 rounded-3xl border border-brand-border-light shadow-sm">
      <div className="mb-8 flex justify-between items-center">
        <h2 className="text-2xl font-bold text-brand-navy">Final Certification Test</h2>
        <span className="px-4 py-1 bg-brand-bg-light text-brand-navy rounded-full text-sm font-semibold border border-brand-border-light">
          Question {currentQuestion + 1} of {questions.length}
        </span>
      </div>

      <div className="mb-10">
        <h3 className="text-xl font-semibold text-brand-navy mb-6">{questions[currentQuestion].q}</h3>
        <div className="space-y-4">
          {questions[currentQuestion].options.map((option, idx) => (
            <button
              key={idx}
              onClick={() => handleAnswer(idx)}
              className="w-full text-left p-5 border border-brand-border-light rounded-xl hover:border-brand-orange hover:bg-brand-orange/5 transition-all text-brand-text-body font-medium"
            >
              {option}
            </button>
          ))}
        </div>
      </div>
      <div className="w-full bg-gray-100 rounded-full h-2">
        <div 
          className="bg-brand-orange h-2 rounded-full transition-all duration-500" 
          style={{ width: `${((currentQuestion) / questions.length) * 100}%` }}
        ></div>
      </div>
    </div>
  );
};
