-- Supabase Schema for Module 2: AI Sales Automation
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: sales_messages
-- Stores generated emails and whatsapp messages before/after approval
CREATE TABLE IF NOT EXISTS public.sales_messages (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    lead_email TEXT NOT NULL,
    lead_name TEXT NOT NULL,
    message_type TEXT NOT NULL CHECK (message_type IN ('email', 'whatsapp')),
    content TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending_approval' CHECK (status IN ('pending_approval', 'approved', 'sent', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: meeting_agendas
-- Stores AI generated discovery call agendas
CREATE TABLE IF NOT EXISTS public.meeting_agendas (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    lead_email TEXT NOT NULL,
    agenda_content TEXT NOT NULL,
    estimated_revenue NUMERIC,
    recommended_services TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: followups
-- Stores follow up sequences generated by AI
CREATE TABLE IF NOT EXISTS public.followups (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    lead_email TEXT NOT NULL,
    sequence_day INTEGER NOT NULL, -- e.g., 1, 3, 7, 14
    content TEXT NOT NULL,
    scheduled_for TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'sent', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: sales_activity
-- Logs all actions for dashboard (Module 5)
CREATE TABLE IF NOT EXISTS public.sales_activity (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    lead_email TEXT NOT NULL,
    activity_type TEXT NOT NULL, -- e.g., 'lead_captured', 'email_sent', 'whatsapp_approved'
    description TEXT,
    ai_tokens_used INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Row Level Security (RLS) Setup
-- For production, restrict access to authenticated service role only
ALTER TABLE public.sales_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_agendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.followups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_activity ENABLE ROW LEVEL SECURITY;

-- Allow full access for service_role (which n8n uses)
CREATE POLICY "Service Role Full Access on sales_messages" ON public.sales_messages FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access on meeting_agendas" ON public.meeting_agendas FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access on followups" ON public.followups FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access on sales_activity" ON public.sales_activity FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
