-- Supabase Schema for Module 13: Analytics, Monitoring & AI Observability

-- 1. System Events
CREATE TABLE IF NOT EXISTS public.system_events (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    module TEXT NOT NULL,
    event_type TEXT NOT NULL,
    severity TEXT DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'error', 'critical')),
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. API Logs
CREATE TABLE IF NOT EXISTS public.api_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    endpoint TEXT NOT NULL,
    method TEXT NOT NULL,
    status_code INT NOT NULL,
    response_time_ms INT,
    client_ip TEXT,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. AI Usage & Observability
CREATE TABLE IF NOT EXISTS public.ai_usage (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    model TEXT NOT NULL,
    prompt_tokens INT DEFAULT 0,
    completion_tokens INT DEFAULT 0,
    total_tokens INT GENERATED ALWAYS AS (prompt_tokens + completion_tokens) STORED,
    latency_ms INT,
    module_source TEXT NOT NULL,
    user_id TEXT,
    cost_estimate NUMERIC(10,6) DEFAULT 0.000000,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Workflow Runs (n8n Observability)
CREATE TABLE IF NOT EXISTS public.workflow_runs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    workflow_id TEXT NOT NULL,
    workflow_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('success', 'error', 'running', 'canceled')),
    execution_time_ms INT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    finished_at TIMESTAMP WITH TIME ZONE
);

-- 5. Workflow Failures
CREATE TABLE IF NOT EXISTS public.workflow_failures (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    workflow_run_id UUID NOT NULL REFERENCES public.workflow_runs(id) ON DELETE CASCADE,
    node_name TEXT NOT NULL,
    error_message TEXT NOT NULL,
    stack_trace TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Webhook Logs
CREATE TABLE IF NOT EXISTS public.webhook_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    source TEXT NOT NULL,
    payload JSONB,
    status TEXT DEFAULT 'received' CHECK (status IN ('received', 'processed', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    actor_id TEXT NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT,
    old_values JSONB,
    new_values JSONB,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Performance Metrics
CREATE TABLE IF NOT EXISTS public.performance_metrics (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    metric_name TEXT NOT NULL,
    value NUMERIC(10,2) NOT NULL,
    unit TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Uptime Checks
CREATE TABLE IF NOT EXISTS public.uptime_checks (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    service_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('up', 'down', 'degraded')),
    response_time_ms INT,
    checked_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. System Alerts
CREATE TABLE IF NOT EXISTS public.system_alerts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    alert_type TEXT NOT NULL,
    message TEXT NOT NULL,
    is_resolved BOOLEAN DEFAULT false,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. AI Cost Tracking (Daily Aggregation)
CREATE TABLE IF NOT EXISTS public.ai_cost_tracking (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    total_tokens INT DEFAULT 0,
    total_cost NUMERIC(10,4) DEFAULT 0.0000,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. Dashboard Snapshots (GPT-4o Insights)
CREATE TABLE IF NOT EXISTS public.dashboard_snapshots (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    snapshot_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    system_health_score INT,
    insights JSONB, -- Generated by AI
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- Views for Analytics
CREATE OR REPLACE VIEW public.vw_system_health AS
SELECT 
    (SELECT COUNT(*) FROM public.uptime_checks WHERE status = 'up' AND checked_at > NOW() - INTERVAL '24 hours') as up_checks,
    (SELECT COUNT(*) FROM public.uptime_checks WHERE checked_at > NOW() - INTERVAL '24 hours') as total_checks,
    (SELECT COUNT(*) FROM public.system_alerts WHERE is_resolved = false) as active_alerts;

CREATE OR REPLACE VIEW public.vw_api_usage AS
SELECT 
    endpoint,
    COUNT(*) as total_requests,
    AVG(response_time_ms) as avg_latency,
    COUNT(*) FILTER (WHERE status_code >= 400) as error_count
FROM public.api_logs
WHERE created_at > NOW() - INTERVAL '30 days'
GROUP BY endpoint;

CREATE OR REPLACE VIEW public.vw_ai_usage AS
SELECT 
    model,
    SUM(total_tokens) as tokens_used,
    SUM(cost_estimate) as estimated_cost,
    AVG(latency_ms) as avg_latency
FROM public.ai_usage
WHERE created_at > NOW() - INTERVAL '30 days'
GROUP BY model;

CREATE OR REPLACE VIEW public.vw_workflow_health AS
SELECT 
    workflow_name,
    COUNT(*) as total_runs,
    COUNT(*) FILTER (WHERE status = 'success') as successful_runs,
    COUNT(*) FILTER (WHERE status = 'error') as failed_runs
FROM public.workflow_runs
WHERE started_at > NOW() - INTERVAL '30 days'
GROUP BY workflow_name;

CREATE OR REPLACE VIEW public.vw_cost_summary AS
SELECT 
    date,
    total_cost
FROM public.ai_cost_tracking
ORDER BY date DESC
LIMIT 30;

-- Indexes for time-series queries
CREATE INDEX idx_system_events_created ON public.system_events(created_at);
CREATE INDEX idx_api_logs_created ON public.api_logs(created_at);
CREATE INDEX idx_ai_usage_created ON public.ai_usage(created_at);
CREATE INDEX idx_workflow_runs_started ON public.workflow_runs(started_at);

-- RLS Configuration (Admin / Service Role Only)
ALTER TABLE public.system_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workflow_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workflow_failures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.uptime_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_cost_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_snapshots ENABLE ROW LEVEL SECURITY;

-- Service Role Policies
CREATE POLICY "Service Role Full Access" ON public.system_events FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.api_logs FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.ai_usage FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.workflow_runs FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.workflow_failures FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.webhook_logs FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.audit_logs FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.performance_metrics FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.uptime_checks FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.system_alerts FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.ai_cost_tracking FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
CREATE POLICY "Service Role Full Access" ON public.dashboard_snapshots FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- Admin Policies
CREATE POLICY "Admin Full Access" ON public.system_events FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.api_logs FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.ai_usage FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.workflow_runs FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.workflow_failures FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.webhook_logs FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.audit_logs FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.performance_metrics FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.uptime_checks FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.system_alerts FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.ai_cost_tracking FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
CREATE POLICY "Admin Full Access" ON public.dashboard_snapshots FOR ALL USING (auth.jwt() ->> 'user_role' = 'admin');
